import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Disable SSR for the entire app to prevent hydration errors caused by browser extensions
export const dynamic = 'force-dynamic'
// We're removing the edge runtime as it's causing issues

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
